"""All constant and arbitrary variables from SAM CRM are defined here, see Appendix for more details"""

import numpy as np

# CONSTANT IN FALL SPEED FORMULA FOR RAIN
a_r = 842  # m^(1-b)s^(-1)

# CONSTANT IN FALL SPEED FORMULA FOR SNOW
a_s = 4.84  # m^(1-b)s^(-1)

# CONSTANT IN FALL SPEED FORMULA FOR GRAUPEL
a_g = 94.5  # m^(1-b)s^(-1)

# CONSTANT IN VENTILATION FACTOR FOR RAIN
a_fr = 0.78

# CONSTANT IN VENTILATION FACTOR FOR SNOW
a_fs = 0.65

# CONSTANT IN VENTILATION FACTOR FOR GRAUPEL
a_fg = 0.78

# EXPONENT IN FALL SPEED FORMULA FOR RAIN
b_r = 0.8

# EXPONENT IN FALL SPEED FORMULA FOR SNOW
b_s = 0.25

# EXPONENT IN FALL SPEED FORMULA FOR GRAUPEL
b_g = 0.5

# CONSTANT INVENTILATION FACTOR FOR RAIN
b_fr = 0.31

# CONSTANT INVENTILATION FACTOR FOR SNOW
b_fs = 0.44

# CONSTANT INVENTILATION FACTOR FOR GRAUPEL
b_fg = 0.31

# RAIN SHAPE FACTOR
C_r = 1.0

# SNOW SHAPE FACTOR
C_s = 2 / np.pi

# GRAUPEL SHAPE FACTOR
C_g = 1.0

# SPECIFIC HEAT OF AIR AT CONSTANT PRESSURE
C_p = 1004  # J/kg/K

# DIFFUSION COEFFICIENT OF WATER VAPOR AT 0°C
D_a = 2.210 * 10 ** (-5)  # m^2/s


# COLLECTION EFFICIENCY OF RAIN FOR CLOUD WATER
E_rc = 1.0

# COLLECTION EFFICIENCY OF SNOW FOR CLOUD WATER
E_sc = 1.0

# COLLECTION EFFICIENCY OF GRAUPEL FOR CLOUD WATER
E_gc = 1.0

# COLLECTION EFFICIENCY OF RAIN FOR CLOUD ICE
E_ri = 1.0

# COLLECTION EFFICIENCY OF SNOW FOR CLOUD ICE
E_si = 0.1

# COLLECTION EFFICIENCY OF GRAUPEL FOR CLOUD ICE
E_gi = 0.1


# GRAVITATIONAL ACCELERATION
g = 9.81  # m^2/s

# LATENT HEAT OF CONDENSATION
L_c = 2.5104 * 10 ** 6  # J/kg


# LATENT HEAT OF SUBLIMATION
L_s = 2.8440 * 10 ** 6  # J/kg


# LATENT HEAT OF FUSION
L_s = 0.3336 * 10 ** 6  # J/kg

# INTERCEPT PARAMETER FOR RAIN
N_0r = 8 * 10 ** 6  # m^(-4)

# INTERCEPT PARAMETER FOR SNOW
N_0s = 3 * 10 ** 6  # m^(-4)


# INTERCEPT PARAMETER FOR GRAUPEL
N_0s = 4 * 10 ** 6  # m^(-4)

# THERMAL CONDUCTIVITY OF AIR AT 0°C
K_a = 2.4 * 10 ** (-2)  # Jm/K/s

# THRESHOL CLOUD WATER FOR AUTOCONVERSION

q_co = 1 * 10 ** (-3)

# THRESHOLD ICE FOR AGGREGATION
q_io = 1 * 10 ** (-4)

# SPECIFIC GAS CONSTANT FOR AIR
R = 287  # J/kg/K

# SPECIFIC GAS CONSTANT FOR WATER VAPOR
R_v = 461  # J/kg/K

# TEMPERATURE THRESHOLD FOR ICE
T_0n = 273.16  # K

# TEMPERATURE THRESHOLD FOR SNOW/GRAUPEL
T_0p = 283.16  # K

# TEMPERATURE THRESHOLD FOR GRAUPEL
T_0g = 283.16  # K

# TEMPERATURE THRESHOLD FOR CLOUD WATER
T_00n = 253.16  # K

# TEMPERATURE THRESHOLD FOR RAIN
T_00p = 268.16  # K

# TEMPERATURE THRESHOLD FOR GRAUPEL
T_00g = 223.16  # K

# TERMINAL VELOCITY FOR CLOUD ICE
V_TI = 0.4  # m/s

# AUTOCONVERSION RATE
alpha = 0.001  # s^-1

# ICE AGGREGATION RATE
beta = 0.001

# REFERENCE AIR DENSITY
rho_0 = 1.29  # kg/m^3

# DENSITY OF RAIN
rho_r = 1000  # kg/m3


# DENSITY OF SNOW
rho_s = 100  # kg/m3

# DENSITY OF GRAUPEL
rho_g = 400  # kg/m3

# DYNAMIC VISCOSITY OF AIR AT 0°C
mu = 1.717 * 10 ** (-5)
